name = "gameapi"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = ""
# database_id = ""

#[[d1_databases]]
#binding = "DB"
#database_name = "experienceapp"
#database_id = "44fa0c44-f943-460b-9b11-500f26a45714"

d1_databases = [{binding="DB", database_name = "experienceapp", database_id = "44fa0c44-f943-460b-9b11-500f26a45714"}]
